apiVersion: v1
kind: Namespace
metadata:
  name: george-fg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: george-fg-deployment
  namespace: george-fg
  labels:
    app: george-fg-app
    env: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: george-fg-app
  template:
    metadata:
      labels:
        app: george-fg-app
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.23
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: downward
          mountPath: /etc/downward
      volumes:
      - name: downward
        downwardAPI:
          items:
          - path: "podName"
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: george-fg-service
  namespace: george-fg
  labels:
    app: george-fg-app
spec:
  type: ClusterIP
  selector:
    app: george-fg-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: george-fg-hpa
  namespace: george-fg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: george-fg-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
